language: node_js
build_environment : Ubuntu1304

before_install:
  - sudo apt-get install python-software-properties -y # for the next command
  # the following repo is not working. TODO: make neko from sources
  # - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains neko
  # - sudo apt-get update                                # pull info from ppa
  # - sudo apt-get install neko -y
  - sudo apt-get install ocaml zlib1g-dev -y

script:
  - make
  # - make tools
  - sudo make install
  - cd tests/unit/
  - mkdir ~/haxelib && haxelib setup ~/haxelib
  - haxe -version
